; ---- HEADER ---- ;

; This ini is an example of what is possible with cINI.
;
; {.name}          -> variable in the current section
; {..name}         -> variable in the parent section
; {parent.name}    -> variable from a named section

[parent]
first_name = "William"
middle_name = "Joseph"
last_name = "Smith"
full_name = "{.first_name} {.middle_name} {.last_name}"
age = 42

[.child]
first_name = "Edward"
last_name = "{parent.last_name}"
full_name = "{.first_name} {.last_name}"
age = 24

[..grandchild]
first_name = "Michael"
full_name = "{.first_name} {...first_name} {..last_name}"
age = 8

[spouse]
first_name = "Jane"
last_name = "{parent.last_name}"
full_name = "{.first_name} {.last_name}"
age = 38

; ---- FOOTER ---- ;